# Generated by Django 3.2.7 on 2021-12-03 17:16

from django.db import migrations, models
import event_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=250)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('image', models.ImageField(default='posts/default.jpg', upload_to=event_api.models.upload_to, verbose_name='Image')),
                ('categories', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], max_length=10)),
                ('published', models.BooleanField()),
                ('paid', models.BooleanField()),
                ('slug', models.SlugField(blank=True, editable=False, max_length=30)),
            ],
        ),
    ]
